# Generated by Django 4.2.23 on 2025-07-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
