# Generated by Django 4.2.23 on 2025-09-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='SupportTicket',
        ),
    ]
